version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: kn_mariadb
    hostname: kn-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: "kn"
      MARIADB_PASSWORD: "TUC-2018"
      MARIADB_ROOT_PASSWORD: "TUC-2018"
      MARIADB_DATABASE: "kn"
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kn_phpmyadmin
    hostname: kn-phpmyadmin
    depends_on: [mariadb]
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "kn-mariadb"
      PMA_PORT: "3306"
      PMA_USER: "kn"
      PMA_PASSWORD: "TUC-2018"
      MYSQL_ROOT_PASSWORD: "TUC-2018"

  odl:
    image: kukkalli/odl-sco:latest
    container_name: kn_odl
    hostname: kn-odl
    ports:
      - "8181:8181"
      - "6633:6633"
      - "6653:6653"
      - "6640:6640"

  orchestrator:
    image: kukkalli/orchestrator:latest
    container_name: kn_orchestrator
    hostname: kn-orchestrator
    depends_on: [mariadb, odl]
    ports:
      - "8080:80"
    environment:
      ODL_IP: "10.10.0.10"
      OPENSTAcK_IP: "10.10.0.21"
