version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: kn_mariadb
    hostname: kn-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: "hanif"
      MARIADB_PASSWORD: "TUC-2018"
      MARIADB_ROOT_PASSWORD: "TUC-2018"
      MARIADB_DATABASE: "orchestrator"
    volumes:
      - /docker-data/db:/var/lib/mysql
      - ./init_db/orchestrator.sql:/docker-entrypoint-initdb.d/orchestrator.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kn_phpmyadmin
    hostname: kn-phpmyadmin
    depends_on: [mariadb]
    ports:
      - "8000:80"
    environment:
      PMA_HOST: "kn-mariadb"
      PMA_PORT: "3306"
      PMA_USER: "hanif"
      PMA_PASSWORD: "TUC-2018"
      MYSQL_ROOT_PASSWORD: "TUC-2018"

  odl:
    image: kukkalli/odl-sco:latest
    container_name: kn_odl
    hostname: kn-odl
    ports:
      - "8181:8181"
      - "6633:6633"
      - "6653:6653"
      - "6640:6640"

  orchestrator:
    image: kukkalli/orchestrator:latest
    container_name: kn_orchestrator
    hostname: kn-orchestrator
    depends_on: [phpmyadmin]
    ports:
      - "80:80"
    environment:
      ODL_IP: "10.10.0.10"
      OPENSTACK_IP: "10.10.0.21"
      MARIADB_HOSTNAME: "kn-mariadb"
      MARIADB_USERNAME: "hanif"
      MARIADB_PASSWORD: "TUC-2018"
      MARIADB_DATABASE: "orchestrator"
    volumes:
      - ./logs/:/app/logs/
#      - ./var-logs/:/var/log/
